apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: websphere-build
      name: websphere
    name: websphere-build
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: websphere:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: image
      git:
        uri: https://github.com/femiosinowo/openshift-websphere.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: centos:latest
          namespace: openshift
      type: Docker
    triggers: []
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: websphere
    name: websphere
  status:
    dockerImageRepository: ""
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: websphere
    name: websphere
  spec:
    replicas: 1
    selector:
      app: websphere
      deploymentconfig: websphere
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: websphere
          deploymentconfig: websphere
      spec:
        containers:
        - image: ' '
          imagePullPolicy: Always
          name: websphere
          ports:
          - containerPort: 9080
            protocol: TCP
          - containerPort: 9443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          #volumeMounts:
          #- mountPath: /websphere-master-data
          #  name: data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        schedulerName: default-scheduler
        #volumes:
        #- emptyDir: {}
        #  name: data
    test: false
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      name: websphere
    name: websphere
  spec:
    ports:
    - name: 9080-tcp
      port: 9080
      protocol: TCP
      targetPort: 9080
    - name: 9443-tcp
      port: 9443
      protocol: TCP
      targetPort: 9443
    selector:
      app: websphere
      deploymentconfig: websphere
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}    
kind: List
metadata: {}