apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: websphere-build
      name: websphere
    name: websphere-build
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: websphere:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: image
      git:
        uri: https://github.com/femiosinowo/openshift-websphere.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: centos:latest
          namespace: openshift
      type: Docker
    triggers: []
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: websphere
    name: websphere
  status:
    dockerImageRepository: ""
kind: List
metadata: {}